### ISSUE TITLE
Etcher pro link?

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher-homepage#120]
Should we have a link directly from https://etcher.io to https://etcher.io/pro ?
@tzikis @konmouz

**Comment by lurch** [comment]
See also https://github.com/resin-io/etcher/pull/2010 for details regarding referral parameters.

**Comment by Shou** [comment]
For now we can add a footer link but ultimately it might make more sense to add an actual section in the `<main>`

**Comment by ckarras11** [comment]
Hello, I have added the Etcher Pro link to the footer.  Also I noticed that if you do not run `yarn run export` the `yarn start` command will fail looking for cache.json in config.  It may be a thought to swap those in the README.

**Comment by jhermsmeier** [comment]
@curcuz should we get this into the main navigation on the Etcher homepage?

**Comment by lurch** [comment]
Closing, as https://www.balena.io/etcher/ now contains a link to https://www.balena.io/etcher/pro
