### ISSUE TITLE
"What's new" link isn't linking to the forum post

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher-homepage#130]
The "See what's new!" link on https://etcher.io/ is currently linking to https://etcher.io/changelog whereas it _should_ be linking to https://forums.resin.io/t/etcher-v1-4-1-release

I did a quick bit of investigation, and it's because the website is looking for a post named `Etcher v1.4.1 release` whereas the [post](https://forums.resin.io/t/etcher-v1-4-1-release/2912) is actually named `Etcher v1.4.1 Release`.

So I guess you could either modify the check at https://github.com/resin-io/etcher-homepage/blob/master/pages/index.js#L44 to be case-insensitive, or you could simply edit the forum post to have a lower-case `r` on `release` :slightly_smiling_face:

**Comment by jhermsmeier** [comment]
Renamed the forum post for now, thanks!
