### ISSUE TITLE
Clarify 32/64 bit version of downloads

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher-homepage#17]
Not everyone is familiar with the "x86"/"x64" notation, should add "x86 (32-bit)" / "x64 (64-bit)" to the OS name as applicable for Linux/Windows.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_oui)

**Comment by lurch** [comment]
As #19 has been merged, I guess this can be closed?
