### ISSUE TITLE
"email link to myself"misbehaves

### ISSUE THREAD

**Issue by imrehg** [resin-io/etcher-homepage#18]
On some mobile clients, the "email link to myself" does seem to error out with an "Email Protection" message. Remember seeing this issue before, but here's an example just received: https://twitter.com/RightSaidJames/status/788098909289742337

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ptj)

**Comment by craigmulligan** [comment]
We've removed the email link to myself link. Now mobile users get the standard drop down.
