### ISSUE TITLE
Add documentation for using AppImage on Linux

### ISSUE THREAD

**Issue by brownjohnf** [resin-io/etcher-homepage#26]
I'm a long-time linux user, but I'd never encountered an AppImage application until etcher and had no idea what to do with it. It's not executable by default, so running it is very counterintuitive. Unix executables don't have extensions, usually. I had to help someone while on support to get it working, too.

I suggest adding instructions about downloading and running chmod +x after extracting, as well as adding a link to http://appimage.org/

**Comment by lurch** [comment]
> It's not executable by default

It _should_ be, that's why we changed them to be packaged in zip format. In fact, I just downloaded and extracted the latest Linux version from the etcher.io website, and:
```
-rwxr-xr-x 1 andrew andrew 56360960 Jan 16 15:13 Etcher-1.0.0-beta.18-linux-x64.AppImage
-rw-rw-r-- 1 andrew andrew 55960697 Jan 17 02:01 Etcher-1.0.0-beta.18-linux-x64.zip
```
?

**Comment by brownjohnf** [comment]
Ah, maybe I'm just acting off of old information then. Though I'm less clear on why the guy on support had info. We should still document that the appimage file is the executable, and isn't another container to be unpacked.

**Comment by lurch** [comment]
Are people still having problems with this, or can this issue be closed now?

**Comment by craigmulligan** [comment]
I'm closing unless there are further issues.
