### ISSUE TITLE
Add CTA to contact hello@etcher.io

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/etcher-homepage#30]
hello@etcher.io is now live; add a CTA to contact us at this email address, perhaps in the footer? @jviotti?

**Comment by jviotti** [comment]
Thanks for the issue @alisondavis17. I sent a quick PR (https://github.com/resin-io/etcher-homepage/pull/32) adding a "Contact" button to the footer that points to that email address, but I'll leave @craig-mulligan to review and merge!
