### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by craigmulligan** [resin-io/etcher-homepage#39]
The site is inherently slow, this is because we send to non-concurrent requests on pageload. First to determine the latest version and the second to get all the links for that version.

The current speeds aren't good, this is a perf test I did this morning: 

<img width="1270" alt="screen shot 2017-04-27 at 08 26 18" src="https://cloud.githubusercontent.com/assets/9499917/25488356/b559790a-2b5e-11e7-9d88-c010e4d39e89.png">

You can see the time to interactive is pretty terrible. There are micro adjustments but basically we need the downloads to be pre rendered if we want to make a real difference here. 

I've been playing around with [next.js](https://github.com/zeit/next.js) which is a server rendering framework for react but with some tweaks it can build static sites. 

I've got a demo here: https://craig-mulligan.github.io/etcher.io/ 

The performance is miles better. 

<img width="1224" alt="screen shot 2017-04-27 at 14 05 45" src="https://cloud.githubusercontent.com/assets/9499917/25488847/fae64010-2b5f-11e7-831a-cad33cd257f5.png">

Something that you won't see in the charts but we also get a boost on second page loads, because we prefetch inject them into the dom like you would with an app. 

If you guys are happy with this we can deploy it, and then set it to rebuild everyday on CI job or just manually deploy it with every release. Later when I have time I'll make it more modular so you can include it easily in the etcher repo.

**Comment by alexandrosm** [comment]
I think preloading the links is the way to go

**Comment by craigmulligan** [comment]
We now preload all the download links so it's faster and users without js enabled can still download. There are more things that can be done to reduce bundle size but they can be tracked in separate issues.

**Comment by alexandrosm** [comment]
Great job craig -- remind me to show you the graphs over on s3stat -- it's
quite... visible :)

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm
