### ISSUE TITLE
Replace all occurrences of "burn" with "flash"

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher-homepage#4]
See https://github.com/resin-io/etcher/issues/297

**Comment by craigmulligan** [comment]
@jviotti good to close?

**Comment by jviotti** [comment]
@craig-mulligan The website still refers to "burn" everywhere. I'll send a PR myself.

**Comment by craigmulligan** [comment]
@jviotti I thought we decided against this change? That's why I proposed closing.

**Comment by jviotti** [comment]
@craig-mulligan Ah really? I don't really remember (we did make the change in the Etcher app itself). Feel free to close this and the PR if so!

**Comment by craigmulligan** [comment]
My only gripe with it is that "burn better" sounds better than "Flash better", so I reckon we the title and replace other instances.
