### ISSUE TITLE
The "see what's new" link is broken

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher-homepage#40]
The forum opens, but shows "Oops! That page doesn’t exist or is private."

**Comment by craigmulligan** [comment]
Yea, I figured we'd keep the same signature (`<version>-release`) for all the posts so I was just building a url with that assumption. I've updated the code to be more robust. You just need to make sure the version is in the title. 

https://github.com/resin-io/etcher-homepage/blob/master/pages/index.js#L20-L22
