### ISSUE TITLE
Change footer text on etcher site 

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/etcher-homepage#44]
Change from current: 

"Etcher is an open source project by [resin.io](https://resin.io) - Modern DevOps for the Industrial Internet of Things"

To:

"Etcher is an open source project by [resin.io](https://resin.io) - modern tools to build your fleet of IoT devices" 

And add resin.io logo similar to:

![screen shot 2017-05-11 at 12 16 02 pm](https://cloud.githubusercontent.com/assets/20308284/25967626/a51beef2-3643-11e7-82cc-ee60c4209ec3.png)

**Comment by lurch** [comment]
Ping @Shou and @konmouz as I guess this also relates to what you're working on?

EDIT: Sorry, forget that! It's late and I'm getting my repos muddled up :-(

**Comment by craigmulligan** [comment]
@alisondavis17 I've changed the text and added the resin logo. lmk if there is anything else to add.

**Comment by alisondavis17** [comment]
@craig-mulligan it still looks the same as the old text to me?

**Comment by craigmulligan** [comment]
@alisondavis17 forgot to deploy, sorry! Should be there now.

**Comment by alisondavis17** [comment]
Looks good!
