### ISSUE TITLE
Firefox on Fedora25 still shows the OSX download

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher-homepage#50]
In Google Chrome on Ubuntu 14.04, when I go to https://etcher.io then the blue download button changes to `Download for Linux x64`.
But when using Firefox on Fedora 25 (I'm testing in VirtualBox) the blue download button just says `Download for OS X`. The only output in the JS Console is `Empty string passed to getElementById().    app.js:22:116926`.

**Comment by craigmulligan** [comment]
hmm, @lurch can you send me the userAgent string for both? You can grab it by opening the console and running `window.navigator.userAgent`. I think on firefox you'll need to run ` window.navigator`

**Comment by lurch** [comment]
Okay, so to even things up (and make things easier to test consistently), I also installed Chromium into that same Fedora 25 virtual machine.

In Chromium (`Version 57.0.2987.133 Fedora Project (64-bit)`), the big blue button initially says `Download for OS X`, but then changes to `Download for Linux x64` after the page has finished loading. `window.navigator.userAgent` reports
```
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```

In Firefox (`53.0 (64-bit)`), the big blue button initially says `Download for OS X` and never changes to anything else. `window.navigator.userAgent` reports
```
"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
```

**Comment by craigmulligan** [comment]
Hey @lurch, thanks for the detail 👍 .

Chromium behaviour is correct, we default to osx (it's the most common visitor os) and then switch the os if detected.

With Firefox it appears the parsing lib we use is giving us the wrong os info. `os.family` should return linux, but with the the ua you provided it returns fedora. See here: https://runkit.com/58a9e04b4771880014cdfc78/5923f33422b35c0012924754 

I've created an [issue](https://runkit.com/58a9e04b4771880014cdfc78/5923f33422b35c0012924754) on platform.js, will try get it sorted there or just add some logic for this case.

**Comment by lurch** [comment]
> we default to osx (it's the most common visitor os)

Wow, really?

It looks like you pasted the wrong URL in your 'issue' link?

**Comment by craigmulligan** [comment]
> we default to osx (it's the most common visitor os) 

No you're right, I checked again and it's actually windows, maybe it was osx at some point in the past. I've made it default to windows now, I've changed the client sniffr, can you check if works as expected?

**Comment by lurch** [comment]
Hmmm, now both Chromium and Firefox display "Download for Windows x86" and never change to anything different :-/

BTW would it be better to default to Windows x64 rather than Windows x86? And IMHO it should probably default to the installer (.exe) rather than portable (.zip) version?

**Comment by craigmulligan** [comment]
Okay works now @lurch. 

re: defaults... I don't know enough about that, we can change it to anything but it's something the etcher team should discuss.

**Comment by lurch** [comment]
Yep, Chromium and Firefox now both display "Download for Linux x86", thanks @craig-mulligan :+1: 

Regarding defaults... (pinging @jviotti @Shou @jhermsmeier @alexandrosm @konmouz )
 - I think if we can't detect the OS, we should default to Windows (etcher.io now does this)
 - I think if we can't detect the CPU, we should default to x64 (etcher.io currently defaults to x86) as I believe 64-bit OSes are far more common than 32-bit OSes now?
 - I think if we have the choice of installer and portable versions (i.e. Windows) then by default we should offer the installer version (.exe) rather than the portable version (.zip) (etcher.io currently defaults to the portable version) as I believe more people will be looking for the installer than the portable version

Other peoples' thoughts?

**Comment by Shou** [comment]
I agree with the points here. After some quick Googling around it seems since Windows 7 brought on a major shift to 64-bit; nothing concrete to show but I'm sure there are some statistics out there. I believe portable installs are a niche, and people who want or need them know to look for that option, so it shouldn't be a problem.

**Comment by jhermsmeier** [comment]
Yeah, agree with what @lurch said regarding the defaults

**Comment by jviotti** [comment]
Sounds good to me!

**Comment by craigmulligan** [comment]
Thanks guys! Closing this issue as it's slightly off topic. I have added @lurch's suggestions to the new one.

**Comment by alexandrosm** [comment]
@craig-mulligan I noticed that android mobile phones also show "download
for windows" now. is this something to look into?

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by craigmulligan** [comment]
@alexandrosm, the os detection lib we use differentiates android from linux but we could add a conditional for that if it makes sense. 

I'm not sure that it's actually useful because etcher wouldn't run on android, so we don't know what their laptop OS is and it's most sensible in that case to default back to the most popular choice (windows).

But maybe there is a better solution than falling back to defaults, open to ideas?

**Comment by lurch** [comment]
> we don't know what their laptop OS is and it's most sensible in that case to default back to the most popular choice (windows).

Sounds sensible to me :+1:

**Comment by jviotti** [comment]
I remember that at some point we discussed having a form saying "put your e-mail and we'll send you the link" for when the OS is not supported (like Android). We can also add a checkbox that says "also subscribe to the newsletter" :)

**Comment by lurch** [comment]
I'm not a smartphone user myself, so take my opinion with a large pinch of salt (as I don't know what other websites do in this situation), but I'd personally be :-1: on Juanchi's suggestion.
 - the etcher.io URL shouldn't be that hard to remember ;)
 - it's already the top link on https://www.google.com/search?q=etcher
 - there might be a danger with assuming a browser is running on an "unsupported OS" and not showing any download links, when in fact the user _is_ running on a supported OS, but there's just a bug in our code that detects the user's OS based on the browser's user-agent string
