### ISSUE TITLE
problem with etcher appimage on raspberry pi

### ISSUE THREAD

**Issue by nigeldodd** [resin-io/etcher-homepage#52]
This is what I get when I install on Raspberry pi

unzip Etcher-1.0.0-linux-x86.zip
sudo ./Etcher-1.0.0-linux-x86.AppImage: Syntax error: "(" unexpected

**Comment by lurch** [comment]
The Raspberry Pi uses an ARM CPU, not an x86 CPU like a PC uses. So unsurprisingly, a program compiled for x86 won't run on a Raspberry Pi.

Other 3rd-party users _have_ managed to get Etcher working on a Raspberry Pi by building it from source (see e.g. https://github.com/resin-io/etcher/issues/1435 and https://github.com/resin-io/etcher/blob/master/docs/RUNNING-LOCALLY.md ) but it's not officially supported.
It's something we _might_ add in future though, so keep your eyes peeled.
