### ISSUE TITLE
Getting "An unexpected error has occurred" on OS X Firefox 53.0.2

### ISSUE THREAD

**Issue by nhstanley** [resin-io/etcher-homepage#53]
Hey all.

I'm getting a strange error when loading https://etcher.io/ on OS X, Firefox 53.0.2. Basically, the web page starts loading, looks like it's loading fine, then suddenly once the page looks like it's fully loaded, I get a blank screen that only has the text "An unexpected error has occurred." 

Turning off uBlockOrigin and Ghostery plugins doesn't fix the issue. I don't think I have any others that should cause this.

**Comment by nhstanley** [comment]
Actually, I just remembered that Firefox now has built in tracking protection. If I also turn that off, the issue is fixed. But that really shouldn't be necessary.

**Comment by craigmulligan** [comment]
Hey @dr-nate, thanks for reporting, should be fixed now. Can you confirm?

**Comment by nhstanley** [comment]
Yup! Thanks!
