### ISSUE TITLE
Update download defaults

### ISSUE THREAD

**Issue by craigmulligan** [resin-io/etcher-homepage#56]
Followed on from #50 
@lurch had some good suggestions on better defaults for the download button. 

> I think if we can't detect the OS, we should default to Windows (etcher.io now does this)
> I think if we can't detect the CPU, we should default to x64 (etcher.io currently defaults to x86) as I believe 64-bit OSes are far more common than 32-bit OSes now?
> I think if we have the choice of installer and portable versions (i.e. Windows) then by default we should offer the installer version (.exe) rather than the portable version (.zip) (etcher.io currently defaults to the portable version) as I believe more people will be looking for the installer than the portable version

**Comment by craigmulligan** [comment]
I've added the defaults as mentioned above. I've also added arch detection, so if we can detect arch from the user agent we'll switch to that instead. 

If no supported os is detected it'll fallback to defaults. cc @lurch @jviotti

**Comment by lurch** [comment]
Great work @craig-mulligan :+1:
