### ISSUE TITLE
Auto detecting wrong arch on windows

### ISSUE THREAD

**Issue by craigmulligan** [resin-io/etcher-homepage#61]
@nistath I saw it incorrectly suggested x86 instead of x64? Could you send me your browser user agent string?

**Comment by nistath** [comment]
It did happen, but I cannot reproduce it...
My string seems fine: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'

**Comment by craigmulligan** [comment]
Thanks! I'll try reproduce locally. 

Btw when did you experience this? Because I updated the arch detection on tuesday - https://github.com/resin-io/etcher-homepage/pull/58

**Comment by nistath** [comment]
On Tuesday, ~an hour before you updated. :P
