### ISSUE TITLE
Remove generated CSS?

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher-homepage#76]
@lurch highlighted in #75 that we have generated CSS in the repository, could we remove this, or is it better kept?

@craig-mulligan

**Comment by craigmulligan** [comment]
Yea it's not needed, the generated css copied from `/static` to `/build/static` when we run `next export` the site. So no reason for `/static/*.css` to be checked-in but `/build/static/*.css` should definitely be.

**Comment by lurch** [comment]
Did you get those last two paths the wrong way around @craig-mulligan ?

**Comment by craigmulligan** [comment]
Nope, `/build/static/*.css` is what is pushed to gh-pages so it should be checked in.

**Comment by craigmulligan** [comment]
Oh wait we are using `gh-pages` which does some git magic to push sub-directories, so yea neither need to be checked in.

**Comment by craigmulligan** [comment]
still on holiday 😴

**Comment by Shou** [comment]
I've removed `/static/*.css` in https://github.com/resin-io/etcher-homepage/pull/75 now.

**Comment by lurch** [comment]
I guess this can be closed?

**Comment by craigmulligan** [comment]
Yip
