### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by craigmulligan** [resin-io/etcher-homepage#79]
Some requests to github seem to timeout in travis CI, which results in false negatives, as seen in #75.

**Comment by lurch** [comment]
Hmmm, given that you're using an `api.github.com` endpoint, perhaps the Travis CI servers are getting blocked for sending too many requests? (rate limiting)
Which might explain why it works sometimes but fails other times?

**Comment by lurch** [comment]
Fixed by #80
